### ISSUE TITLE
Consider changing the licence to LGPL

### ISSUE THREAD

**Issue by kuzavas** [aewallin/allantools#11]
Changing licence to "[GNU Lesser General Public License (LGPL) version 2.1](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html) or later" would allow wider usage of allantools while still requiring distributing changes to the library. Example LGPL usage can be seen at [FFmpeg](https://www.ffmpeg.org/legal.html).

**Comment by aewallin** [comment]
I don't see this happening.
Anyone can use the library privately with whatever modification they want. If you publish please abide by the GPL. I think that's fair enough.
