### ISSUE TITLE
Windows build failing on Travis CI

### ISSUE THREAD

**Issue by aewallin** [aewallin/allantools#127]
the travis log gives some clues on what is wrong with the windows build

`The command "python -m pip install -v ." failed and exited with 1 during .`

`   ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)`

` urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>`

**Comment by fmeynadier** [comment]
May be linked with this warning ?

"Please be aware travis-ci.org will be shutting down by end of May 2021. Please consider migrating to travis-ci.com. "

In fact I have seen this kind of warning for a long time but never really took the time to dig it further.

I don't know exactly how much work this involves... I may have some time to look at that, but later in the month !

**Comment by aewallin** [comment]
It looks like travis-ci.org and travis-ci.com accounts are separate things.

To use the new travis-ci.com it looks like I have to sign up for their beta program. The free account includes some amount of 'tokens', which I assume are then consumed whenever builds are triggered.

I can try to test how travis-ci.com works sometime during the coming days.

**Comment by fmeynadier** [comment]
Either that or switch to "github actions", as advertised on github for some time in the past...

Hints found on the web:

https://tomasvotruba.com/blog/2020/01/27/switch-travis-to-github-actions-to-reduce-stress/

I really wanted to spend a little time figuring out what all this implies, but I only skimmed the surface before reaching the deadline ! I don't know if travis-ci decided to change its business model first, or github/MS decided to push their own solution, or both, but I think the bottom line is we can recover roughly the same functionnalities but have to do some reconfiguration...

**Comment by aewallin** [comment]
github actions/workflow seems to work on ubuntu with python 3.7, 3.8, 3.9

pull requests are welcome, if someone is interested in mac and windows workflows

closing this issue, we don't use travis anymore.
