### ISSUE TITLE
Matplotlib Warning: `UserWarning: First parameter to grid() is false, but line properties are supplied. ...`

### ISSUE THREAD

**Issue by DietBru** [aewallin/allantools#128]
Hello,
when using matplotib 3.4.2, I am getting the warning:
    
       UserWarning: First parameter to grid() is false, but line properties are supplied. The grid will be enabled.

It is caused by the command

       self.ax.grid(grid, which="minor", ls="-", color='0.65')

from file `plot.py`, line 95. Replacing it with

        if grid:  # if/else to silence matplotlib warning
            self.ax.grid(grid, which="minor", ls="-", color='0.65')
            self.ax.grid(grid, which="major", ls="-", color='0.25')
        else:
            self.ax.grid(False)

silences this warning.
Thanks.

**Comment by aewallin** [comment]
thanks, I noticed the same warning on a newly installed computer. I guess it is related to a new matplotlib version.

I can make a commit/pull-request with your fixes in a few days - thanks for posting the issue and a proposed fix.
