### ISSUE TITLE
Make a new release on pypi.python.org

### ISSUE THREAD

**Issue by kuzavas** [aewallin/allantools#15]
It would be very helpful if a new release would be made at pypi.python.org. It would enable Python 3 compatibility.

**Comment by aewallin** [comment]
Hi, I have tried to make a new release on PyPi, bumping the version number to a year.month format of 2016.2. 
Please test on various platforms and report any issues! Thanks.

**Comment by kuzavas** [comment]
I have tried 2016.2 in following platforms:

- Debian, amd64, Python 2.7, all tests OK.
- Debian, amd64, Python 3.5, all tests OK.
- Windows 10, amd64, Python 3.5, all tests OK.

There were some not very clear errors using older numpy from Debian packages but I have not noticed anything wrong with a newly install numpy from pip.

Also, there was some warnings running ipython notebooks:

(taus,devA) = allantools.three_cornered_hat_phase(phaseAB,phaseBC,phaseCA,rate,t, allantools.mdev_phase)

c:\users\naudotojas\appdata\local\programs\python\python35\lib\site-packages\allantools\allantools.py:166: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future

  d0 = data[0:m]

c:\users\naudotojas\appdata\local\programs\python\python35\lib\site-packages\allantools\allantools.py:167: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future

  d1 = data[m:2*m]

c:\users\naudotojas\appdata\local\programs\python\python35\lib\site-packages\allantools\allantools.py:168: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future

  d2 = data[2*m:3*m]

c:\users\naudotojas\appdata\local\programs\python\python35\lib\site-packages\allantools\allantools.py:174: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future

  d3 = data[3*m:]

c:\users\naudotojas\appdata\local\programs\python\python35\lib\site-packages\allantools\allantools.py:175: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future

  d2 = data[2*m:]

c:\users\naudotojas\appdata\local\programs\python\python35\lib\site-packages\allantools\allantools.py:176: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future

  d1 = data[1*m:]

c:\users\naudotojas\appdata\local\programs\python\python35\lib\site-packages\allantools\allantools.py:1148: RuntimeWarning: invalid value encountered in sqrt

  dev_a = np.sqrt(var_a)
