### ISSUE TITLE
GPU support?

### ISSUE THREAD

**Issue by alex-c2** [aewallin/allantools#151]
Is the current version compatible with GPU acceleration via CuPy etc.?

**Comment by aewallin** [comment]
Hi, I am not familiar with CyPu or other GPU-acceleration libraries. Most algorithms use numpy quite heavily, so should benefit from things that make numpy run faster.
Do you have a particular application in mind where performance is an issue?

**Comment by aewallin** [comment]
closing for now, please reopen if there are real use-cases that benefit from GPU-acceleration, and this can be implemented without major rework of the algorithms.
