### ISSUE TITLE
Latest release 2019.9 produces `SyntaxWarnings` in Python ^3.8

### ISSUE THREAD

**Issue by lochsh** [aewallin/allantools#152]
For example:

```python
/path/to/venv/lib/python3.8/site-packages/allantools/ci.py:103: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if (dev_type is "hdev") or (dev_type is "ohdev"):
```

There are a lot of `is` comparisons with string literals in the 2019.9 release, which is the latest release available on pypi.org. From Python 3.8 onwards (I think) this causes a `SyntaxWarning` as there's no guarantee in the language spec that the strings will be interned such that this will evaluate to `True` for two strings with the same value.

It looks like these comparisons are fixed in the latest `master` code, but there is no release with these fixes. I also note that the most recent GitHub release is 2019.7 rather than 2019.9.

Is there a plan to do a newer release with the fixes any time soon? Or a patch release to fix this specific issue?

Many thanks!

**Comment by fmeynadier** [comment]
Not all issues listed in #101 did get an answer, but maybe it would be good indeed to assemble an intermediate release... @aewallin can I help ? I am not super familiar with the process of uploading to pypi, but if you think that for example moving from setup.py to pyproject.toml might help this is something I can do.

**Comment by aewallin** [comment]
I agree, a new release is a good idea. I will see what I can do over the weekend.

**Comment by aewallin** [comment]
There is now a new release tagged on github, and uploaded to PyPi  https://pypi.org/project/AllanTools/
The source distribution is now built based on a pyproject.toml file (old setup.py etc. files removed).

I'm not sure if the conda package build will trigger automatically - or if some manual work is required. I guess we will know in 1-2 days if the conda package is built automatically.

I would encourage everyone to test the new package, on as many platforms as possible (windows, linux, mac, etc.)

**Comment by aewallin** [comment]
I have updated the conda-forge recipe, and the conda package should also now be updated to the latest version https://anaconda.org/conda-forge/allantools

**Comment by aewallin** [comment]
closing this for now - please create new issues if the new release/package has some problems.
