### ISSUE TITLE
Pypi published version 2024.04 tries to import "simps" from scipy.integrate (instead of "simpson")

### ISSUE THREAD

**Issue by johann-petrak** [aewallin/allantools#161]
In line 114 of allantools.py
```
from scipy.integrate import simps  # used in psd2allan()
```

**Comment by fmeynadier** [comment]
This looks like a regression from #159...

**Comment by aidanmontare-fed** [comment]
I think the change is already in, and this will be fixed in the next release?

**Comment by johann-petrak** [comment]
Good, would there be a release soon, as the current release seems to be unusable for me as it fails when trying to just importing the package already?

**Comment by aewallin** [comment]
I bumped the version to 2024.06, and updated the PyPi package. Conda will take a bit longer..
Could you test and see if this works better?

**Comment by johann-petrak** [comment]
Thank you, that import error is now fixed with the latest version!
