### ISSUE TITLE
Add version number (__version__ )

### ISSUE THREAD

**Issue by dinya** [aewallin/allantools#19]
Is it possible to add ``__version__`` to the package?

**Comment by fmeynadier** [comment]
Interestingly, there are 7 (!) ways to share version number between the package manager and the source code, none of them looking particularly elegant to me... :

http://python-packaging-user-guide.readthedocs.org/en/latest/single_source_version/

Maybe solution number 5 would induce the smallest code modifications, at the expense of importing the pkg_resources module...

Solutions 3 and 4 suppose to devote a specific, separate file containing only one line for that. This is probably the most simple solution, but I wonder how often one forgets to bump version number in this case...

**Comment by aewallin** [comment]
I have added __version__ directly to allantools.py
This requires manual updates to both __version__ and setup.py when a new version is released. If someone wants to implement something smarter I will accept a pull request - just keep it as simple as possible.
