### ISSUE TITLE
documentation: readthedocs site not showing 'autofunction' documentation

### ISSUE THREAD

**Issue by aewallin** [aewallin/allantools#32]
For some reason the 'autofunction' documentation that is generated OK by 'make html' offline does not show up on readthedocs.
(is it because we are now using latex math in the docstrings?)

**Comment by fmeynadier** [comment]
I confirm make html works fine for me, too...

ReadTheDocs help mentions a "Builds" tab where errors are stored : 
http://read-the-docs.readthedocs.org/en/latest/faq.html#my-project-isn-t-building-with-autodoc

Do you see anything there that might give a hint ?

**Comment by aewallin** [comment]
right, found the Build-tab on readthedocs. For the latest master the error message is:

> python /home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/latest/bin/pip install --exists-action=w --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/allantools/.cache/pip -rrequirements.txt
> Collecting numpy (from -r requirements.txt (line 1))
> /home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/latest/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
>   InsecurePlatformWarning
>   Downloading numpy-1.11.0.tar.gz (4.2MB)
> Collecting numpydoc (from -r requirements.txt (line 2))
>   Downloading numpydoc-0.6.0.tar.gz
> Collecting allantools (from -r requirements.txt (line 3))
>   Downloading AllanTools-2016.3.tar.gz
> Collecting scipy (from allantools->-r requirements.txt (line 3))
>   Downloading scipy-0.17.0.tar.gz (12.4MB)
> Building wheels for collected packages: numpy, numpydoc, allantools, scipy
>   Running setup.py bdist_wheel for numpy
>   Stored in directory: /home/docs/checkouts/readthedocs.org/user_builds/allantools/.cache/pip/wheels/dc/c6/37/0a82876d354006c8bfec830bffcb455215968d8e3c22b9e155
> Exception:
> Traceback (most recent call last):
>   File "/home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/latest/local/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
>     status = self.run(options, args)
>   File "/home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/latest/local/lib/python2.7/site-packages/pip/commands/install.py", line 305, in run
>     wb.build(autobuilding=True)
>   File "/home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/latest/local/lib/python2.7/site-packages/pip/wheel.py", line 791, in build
>     session=self.requirement_set.session)
>   File "/home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/latest/local/lib/python2.7/site-packages/pip/download.py", line 814, in unpack_url
>     unpack_file_url(link, location, download_dir)
>   File "/home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/latest/local/lib/python2.7/site-packages/pip/download.py", line 723, in unpack_file_url
>     unpack_file(from_path, location, content_type, link)
>   File "/home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/latest/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 645, in unpack_file
>     flatten=not filename.endswith('.whl')
>   File "/home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/latest/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 535, in unzip_file
>     data = zip.read(name)
>   File "/usr/lib/python2.7/zipfile.py", line 935, in read
>     return self.open(name, "r", pwd).read()
>   File "/usr/lib/python2.7/zipfile.py", line 968, in open
>     raise BadZipfile("Truncated file header")
> BadZipfile: Truncated file header
> You are using pip version 7.1.2, however version 8.1.1 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by aewallin** [comment]
for the 2016.3 tag (which readthedocs considers latest stable release) the error is different:

>  python /home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/stable/bin/pip install --exists-action=w --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/allantools/.cache/pip -rrequirements.txt
> Collecting numpy (from -r requirements.txt (line 1))
>   Using cached numpy-1.11.0.tar.gz
> Collecting numpydoc (from -r requirements.txt (line 2))
>   Using cached numpydoc-0.6.0.tar.gz
> Collecting allantools (from -r requirements.txt (line 3))
>   Using cached AllanTools-2016.3.tar.gz
> Collecting scipy (from allantools->-r requirements.txt (line 3))
> /home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/stable/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
>   InsecurePlatformWarning
>   Downloading scipy-0.17.0.tar.gz (12.4MB)
> Building wheels for collected packages: numpy, numpydoc, allantools, scipy
>   Running setup.py bdist_wheel for numpy
>   Stored in directory: /home/docs/checkouts/readthedocs.org/user_builds/allantools/.cache/pip/wheels/dc/c6/37/0a82876d354006c8bfec830bffcb455215968d8e3c22b9e155
>   Running setup.py bdist_wheel for numpydoc
>   Stored in directory: /home/docs/checkouts/readthedocs.org/user_builds/allantools/.cache/pip/wheels/dc/57/4b/208d9fe5126068db37c0ffb353d12efdb81a8687a652f9e92c
>   Running setup.py bdist_wheel for allantools
>   Stored in directory: /home/docs/checkouts/readthedocs.org/user_builds/allantools/.cache/pip/wheels/72/6c/5b/1e3d7d3f0fe1d34456225a7860d721fda9ffd25ed7c1e84105
>   Running setup.py bdist_wheel for scipy
>   Complete output from command /home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/stable/bin/python -c "import setuptools;__file__='/tmp/pip-build-eW5bcz/scipy/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmps4YQXdpip-wheel-:
>   Traceback (most recent call last):
>     File "<string>", line 1, in <module>
>     File "/tmp/pip-build-eW5bcz/scipy/setup.py", line 265, in <module>
>       setup_package()
>     File "/tmp/pip-build-eW5bcz/scipy/setup.py", line 253, in setup_package
>       from numpy.distutils.core import setup
>   ImportError: No module named numpy.distutils.core
>   
>   ----------------------------------------
>   Failed building wheel for scipy
> Successfully built numpy numpydoc allantools
> Failed to build scipy
> Installing collected packages: numpy, numpydoc, scipy, allantools
>   Running setup.py install for scipy
>     Complete output from command /home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/stable/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-eW5bcz/scipy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-QYc5dr-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/stable/include/site/python2.7/scipy:
>     lapack_opt_info:
>     openblas_lapack_info:
>       libraries openblas not found in ['/home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/stable/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
>       NOT AVAILABLE
>     
>     lapack_mkl_info:
>     mkl_info:
>       libraries mkl,vml,guide not found in ['/home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/stable/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
>       NOT AVAILABLE
>     
>       NOT AVAILABLE
>     
>     atlas_3_10_threads_info:
>     Setting PTATLAS=ATLAS
>       libraries tatlas,tatlas not found in /home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/stable/lib
>       libraries lapack_atlas not found in /home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/stable/lib
>       libraries tatlas,tatlas not found in /usr/local/lib
>       libraries lapack_atlas not found in /usr/local/lib
>       libraries tatlas,tatlas not found in /usr/lib
>       libraries lapack_atlas not found in /usr/lib
>       libraries tatlas,tatlas not found in /usr/lib/x86_64-linux-gnu
>       libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
>     <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
>       NOT AVAILABLE
>     
>     atlas_3_10_info:
>       libraries satlas,satlas not found in /home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/stable/lib
>       libraries lapack_atlas not found in /home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/stable/lib
>       libraries satlas,satlas not found in /usr/local/lib
>       libraries lapack_atlas not found in /usr/local/lib
>       libraries satlas,satlas not found in /usr/lib
>       libraries lapack_atlas not found in /usr/lib
>       libraries satlas,satlas not found in /usr/lib/x86_64-linux-gnu
>       libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
>     <class 'numpy.distutils.system_info.atlas_3_10_info'>
>       NOT AVAILABLE
>     
>     atlas_threads_info:
>     Setting PTATLAS=ATLAS
>       libraries ptf77blas,ptcblas,atlas not found in /home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/stable/lib
>       libraries lapack_atlas not found in /home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/stable/lib
>       libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
>       libraries lapack_atlas not found in /usr/local/lib
>       libraries ptf77blas,ptcblas,atlas not found in /usr/lib
>       libraries lapack_atlas not found in /usr/lib
>       libraries ptf77blas,ptcblas,atlas not found in /usr/lib/x86_64-linux-gnu
>       libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
>     <class 'numpy.distutils.system_info.atlas_threads_info'>
>       NOT AVAILABLE
>     
>     atlas_info:
>       libraries f77blas,cblas,atlas not found in /home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/stable/lib
>       libraries lapack_atlas not found in /home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/stable/lib
>       libraries f77blas,cblas,atlas not found in /usr/local/lib
>       libraries lapack_atlas not found in /usr/local/lib
>       libraries f77blas,cblas,atlas not found in /usr/lib
>       libraries lapack_atlas not found in /usr/lib
>       libraries f77blas,cblas,atlas not found in /usr/lib/x86_64-linux-gnu
>       libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
>     <class 'numpy.distutils.system_info.atlas_info'>
>       NOT AVAILABLE
>     
>     /home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/stable/local/lib/python2.7/site-packages/numpy/distutils/system_info.py:1542: UserWarning:
>         Atlas (http://math-atlas.sourceforge.net/) libraries not found.
>         Directories to search for the libraries can be specified in the
>         numpy/distutils/site.cfg file (section [atlas]) or by setting
>         the ATLAS environment variable.
>       warnings.warn(AtlasNotFoundError.__doc__)
>     lapack_info:
>       libraries lapack not found in ['/home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/stable/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
>       NOT AVAILABLE
>     
>     /home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/stable/local/lib/python2.7/site-packages/numpy/distutils/system_info.py:1553: UserWarning:
>         Lapack (http://www.netlib.org/lapack/) libraries not found.
>         Directories to search for the libraries can be specified in the
>         numpy/distutils/site.cfg file (section [lapack]) or by setting
>         the LAPACK environment variable.
>       warnings.warn(LapackNotFoundError.__doc__)
>     lapack_src_info:
>       NOT AVAILABLE
>     
>     /home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/stable/local/lib/python2.7/site-packages/numpy/distutils/system_info.py:1556: UserWarning:
>         Lapack (http://www.netlib.org/lapack/) sources not found.
>         Directories to search for the sources can be specified in the
>         numpy/distutils/site.cfg file (section [lapack_src]) or by setting
>         the LAPACK_SRC environment variable.
>       warnings.warn(LapackSrcNotFoundError.__doc__)
>       NOT AVAILABLE
>     
>     Running from scipy source directory.
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-eW5bcz/scipy/setup.py", line 265, in <module>
>         setup_package()
>       File "/tmp/pip-build-eW5bcz/scipy/setup.py", line 262, in setup_package
>         setup(**metadata)
>       File "/home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/stable/local/lib/python2.7/site-packages/numpy/distutils/core.py", line 135, in setup
>         config = configuration()
>       File "/tmp/pip-build-eW5bcz/scipy/setup.py", line 182, in configuration
>         config.add_subpackage('scipy')
>       File "/home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/stable/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 1003, in add_subpackage
>         caller_level = 2)
>       File "/home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/stable/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 972, in get_subpackage
>         caller_level = caller_level + 1)
>       File "/home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/stable/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 909, in _get_configuration_from_setup_py
>         config = setup_module.configuration(*args)
>       File "scipy/setup.py", line 15, in configuration
>         config.add_subpackage('linalg')
>       File "/home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/stable/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 1003, in add_subpackage
>         caller_level = 2)
>       File "/home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/stable/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 972, in get_subpackage
>         caller_level = caller_level + 1)
>       File "/home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/stable/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 909, in _get_configuration_from_setup_py
>         config = setup_module.configuration(*args)
>       File "scipy/linalg/setup.py", line 20, in configuration
>         raise NotFoundError('no lapack/blas resources found')
>     numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
>     
>     ----------------------------------------
> Command "/home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/stable/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-eW5bcz/scipy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-QYc5dr-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/docs/checkouts/readthedocs.org/user_builds/allantools/envs/stable/include/site/python2.7/scipy" failed with error code 1 in /tmp/pip-build-eW5bcz/scipy
> You are using pip version 7.1.2, however version 8.1.1 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by aewallin** [comment]
if scipy is problematic, it is used only on two lines of allantools.py, where the function scipy.stats.chi2.ppf() is called.

It would probably not be very hard to implement scipy.stats.chi2.ppf() in pure python relying only on numpy:
http://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.chi2.html

**Comment by aewallin** [comment]
This is now solved, by checking this box under advanced settings on the readthedocs site:

**

> Use system packages: Give the virtual environment access to the global site-packages dir.

**
