### ISSUE TITLE
if not np.any(taus) - fails for taus='all' 'octave' 'decade'

### ISSUE THREAD

**Issue by aewallin** [aewallin/allantools#35]
tau_generator() needs a fix so that it can handle all the possible inputs:

1. no taus parameter supplied by user, should default to 'octave'
2. numpy.array supplied
3. text parameter 'all', 'octave', or 'decade' supplied.

currently I get:
    if not np.any(taus): # empty or no tau-list supplied
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 1840, in any
    return arr.any(axis=axis, out=out)
  File "/usr/lib/python2.7/dist-packages/numpy/core/_methods.py", line 33, in _any
    keepdims=keepdims)
TypeError: cannot perform reduce with flexible type

**Comment by fmeynadier** [comment]
Still working on it, but this should look like this at the end...
