### ISSUE TITLE
Additions/changes/issues before 2016.4?

### ISSUE THREAD

**Issue by aewallin** [aewallin/allantools#40]
Are there any major issues, questions, or changes that need to be fixed before the next release 2016.4?

I think we have made good progress and would want the new API out as soon as possible.

please discuss below.

**Comment by fmeynadier** [comment]
I'd vote for a very quick release, to avoid people having to change function calls twice...

**Comment by aewallin** [comment]
2016.4 now tagged and uploaded to PyPi.

version numbers are cheap anyway, so let's just update to 2016.4.1 if any bugs are found :)

test reports from various platforms such as python 3, windows, mac, etc. are welcome!
