### ISSUE TITLE
Documentation not updated 

### ISSUE THREAD

**Issue by cdboschen** [aewallin/allantools#55]
I was unable to follow the example in the getting started page (using Version 2016.11) upon first review of this code:
 
https://github.com/aewallin/allantools/blob/master/docs/getting_started.rst

Specifically the "Frequency data example". 

Upon reviewing the code it looks like the correct expression (using the earlier API that is still valid) should be: 

From (sic):
(t2, ad, ade, adn) = allantools.oadev(freqyency=y, rate=r, taus=t)    

To:
(t2, ad, ade, adn) = allantools.oadev(y, rate=r, data_type=”freq”, taus=t)    

The other examples shown may have a similar issue. Also it would be good to show on this page how the new API can be used.

**Comment by fmeynadier** [comment]
Good catch, thanks.

I wonder if this section is still needed anyway, as it seems a bit redundant with http://allantools.readthedocs.io/en/latest/readme_copy.html#usage

Any thoughts ?

**Comment by aewallin** [comment]
It would be nice if the documentation could include actual running code, e.g. tests from a /test directory - so the tests would run automatically and errors in the documentation would be caught immediately.

**Comment by cdboschen** [comment]
Yes agreed, good to have one readme in one location to avoid future misalignment and easier for new users like me. The content of this one was good in terms of providing a quick start.

Dan

**Comment by aewallin** [comment]
closed via #98
