### ISSUE TITLE
test_tau_reduction fails

### ISSUE THREAD

**Issue by aewallin** [aewallin/allantools#61]
On some (newer?) python versions the test_tau_reduction fails with an output of
E       IndexError: boolean index did not match indexed array along dimension 0; dimension is 42 but corresponding boolean dimension is 41

the problem seems to be rounding-error in tau_reduction() around line 1411 in allantools.py

**Comment by aewallin** [comment]
This is now at least temporarily patched with:
`    
     if len(keep)>len(ms):
        keep = keep[:len(ms)] # ugly patch for issue..
    elif len(keep)<len(ms):
        ms = ms[:len(keep)]
`

**Comment by fmeynadier** [comment]
I don’t understand how it could have worked in the first place: unless I miss something it is quite obvious that differences of [:-1] and [1:] arrays will be 1 element shorter than the initial size. Besides its inclusion made the CI fail, so I guess it is not a python version problem.

I did not do this commit  (b26b9b511f9bcb2f83ded2146473f90e0ad90510), author is indicated to be dr. ir. T. J. Pinkert. I don’t know if it is a port of a particular implementation: if it is, may be he could point us to the source implementation or clarify what he had in mind ? 

Anyway, just shortening ms by chopping the last item makes unit tests happy. I send a PR with the proposed change.

**Comment by aewallin** [comment]
closed by cb2bdec
