### ISSUE TITLE
Why is the length of violet noise samples-1?

### ISSUE THREAD

**Issue by jondoesntgit** [aewallin/allantools#74]
It's easy enough to correct on my end, but it seems inconsistent.

https://github.com/aewallin/allantools/blob/master/tests/functional_tests/test_noise.py

**Comment by aewallin** [comment]
Looks like diff( random(num_points) ) could be changed to diff( random(num_points+1) ) over here
https://github.com/aewallin/allantools/blob/master/allantools/noise.py#L71

I agree that for consistency all noise-functions should return the same number of points.
Another questions is if we want to keep all the individual noise-generators or use Kasdin&Walter for everything?
