### ISSUE TITLE
readme now in two places?

### ISSUE THREAD

**Issue by aewallin** [aewallin/allantools#8]
We should avoid duplicating information, but we now have mostly the same information in README.md which is used for the github frontpage, as well as docs/index.rst which is used to generate the sphinx documentation frontpage.

is there a solution that uses one single source file for both?

**Comment by mivade** [comment]
Github can render RST files just fine. The Sphinx index page can then use the `include` directive to include the contents of the README.

**Comment by aewallin** [comment]
this is now fixed.
