### ISSUE TITLE
move stable32-like plotting to Plot()

### ISSUE THREAD

**Issue by aewallin** [aewallin/allantools#84]
stable32-like plotting functions (#83) are now in /examples - these could be merged with the existing Plot() object - perhaps with a few style-options to the user.

Use of special characters in pylab (or matplotlib?) - like tau and sigma - seems to require python3. If someone is eager to support python 2.x also then this would be a slight improvement.

**Comment by fmeynadier** [comment]
Good idea to put them there (and thank you @yxie-git for contributing that). I think it is useful to have this kind of plots, but I did not really see how to merge that properly with existing code. 

In fact I am still not 100% convinced it should be merged in Plot() : having a predefined, familiar plot format sounds like a good idea but in practice I think users will want to tweak it as soon as they use it (as in issue #70)... I will try to think about it.

Concerning python 2.X support : [clock](https://pythonclock.org/) is ticking... Numpy is in the process of deprecating 2.7 (no more automated testing in the dev branch: https://github.com/numpy/numpy/pull/12506). So personally I would not spend too much time trying to display correctly these characters in 2.X...

**Comment by aewallin** [comment]
OK, if there is no straightforward merge I will close this issue - at least for now.
