### ISSUE TITLE
Cython required?

### ISSUE THREAD

**Issue by aewallin** [aewallin/allantools#9]
We now have a dependency on Cython in setup.py

Less dependencies and complexity is better, so are there any benchmarks published that show improved performance using Cython?

If no significant speedup (2x ?) can be measured, I suggest removing Cython.

**Comment by telegraphic** [comment]
Yeah, may be good to remove, can always look at speed again later if someone really needs it.

Btw, I think think the bottleneck import creeped back in in allantools.py lines 44-48:

```
try:
    import bottleneck as bn
    USE_BOTTLENECK = True
except ImportError:
    USE_BOTTLENECK = False
```

I think all that code's been removed now, so it'd be safe to remove the import too.

**Comment by aewallin** [comment]
removed cython and bottleneck. if someone can demonstrate that more performance is required and can be provided by cython then we may reintroduce this dependency.
