### ISSUE TITLE
remove slow tests

### ISSUE THREAD

**Issue by aewallin** [aewallin/allantools#96]
Any single test should probably not take more than 1s to run. If it's longer just have it as an example - but not as a test that we run continuously.

Currently these tests take longer than 1s on my machine:
5.65s call     tests/gps/test_gps.py::TestGPS::test_tdev_ci_and_noiseID
5.63s call     tests/gps/test_gps.py::TestGPS::test_mdev_ci_and_noiseID
5.61s call     tests/gps/test_gps.py::TestGPS::test_ohdev_ci_and_noiseID
5.60s call     tests/gps/test_gps.py::TestGPS::test_hdev_ci_and_noiseID
5.57s call     tests/gps/test_gps.py::TestGPS::test_oadev_ci_and_noiseID
5.36s call     tests/gps/test_gps.py::TestGPS::test_adev_ci_and_noiseID
4.04s call     tests/phasedat/test_phasedat.py::TestPhaseDat::test_phasedat_mtotdev
3.76s call     tests/phasedat/test_phasedat.py::TestPhaseDat::test_phasedat_ttotdev
3.43s call     tests/phasedat/test_phasedat.py::TestPhaseDat::test_phasedat_htotdev
2.21s call     tests/realtime/test_rt_auto_AF.py::test_tdev_rt_autoAF
1.97s call     tests/realtime/test_rt_auto_AF.py::test_oadev_rt_autoAF
1.84s call     tests/realtime/test_rt_auto_AF.py::test_ohdev_rt_autoAF
1.19s call     tests/gps/test_gps.py::TestGPS::test_noise_id

**Comment by aewallin** [comment]
updated list of slow tests is now

3.06s call     tests/phasedat/test_phasedat.py::TestPhaseDat::test_phasedat_mtotdev
3.05s call     tests/phasedat/test_phasedat.py::TestPhaseDat::test_phasedat_ttotdev
2.88s call     tests/phasedat/test_phasedat.py::TestPhaseDat::test_phasedat_htotdev
1.10s call     tests/gps/test_gps.py::TestGPS::test_mdev_ci_and_noiseID
1.10s call     tests/gps/test_gps.py::TestGPS::test_oadev_ci_and_noiseID
1.08s call     tests/gps/test_gps.py::TestGPS::test_tdev_ci_and_noiseID
1.06s call     tests/gps/test_gps.py::TestGPS::test_ohdev_ci_and_noiseID
1.06s call     tests/gps/test_gps.py::TestGPS::test_adev_ci_and_noiseID
1.05s call     tests/gps/test_gps.py::TestGPS::test_hdev_ci_and_noiseID
1.02s call     tests/gps/test_gps.py::TestGPS::test_noise_id

**Comment by fmeynadier** [comment]
Until now the solution was to mark them as "slow" using the `@pytest.mark.slow` decorator, then exclude them from the routine tests using (for example) `pytest-3 -k "not (slow or fails)" --doctest-glob='*.rst'`. 

Do you suggest to remove them from the "tests" directory and/or from the pytest framework ?

**Comment by aewallin** [comment]
The remaining tests are mtotdev(), ttotdev() and htotdev() tests for the phase.dat file - so in fact the tests are slow because the algorithm is very slow as noted in #21 .
The Stable32/FrequenC code-base could be checked to see if there is any smart way to speed up the calculation.

Yes, marking them with @pytest.mark.slow is a good idea!
Let's keep them in the tests-folder for now - but try to keep the test-times at/below 1s in the future.

**Comment by aewallin** [comment]
I now found a fix for #21 - so this issue is not so relevant anymore.
closing.
