### ISSUE TITLE
Inconsistency in pink noise data type

### ISSUE THREAD

**Issue by theophilec** [aewallin/allantools#99]
Seems that `pink` noise generation (using `noise.pink`) produces a `list` whereas the other noise functions produce `numpy.ndarray`.

Could we just add a `return np.array(...)` to the return line in the the `pink` function for consistency, or is this intended behavior?

**Comment by fmeynadier** [comment]
There also is an inconsistency in parameters for the number of points :

```
def white(num_points=1024, b0=1.0, fs=1.0):
def brown(num_points=1024, b2=1.0, fs=1.0):
def violet(num_points):
def pink(N, depth=80):
```

We should probably agree on N, num_points or numpoints=1024 for all kinds.

(and/or replace these functions with calls to Noise() class in noise_kasdin.py ? I  thought this had been suggested somewhere else but can't find where)

**Comment by aewallin** [comment]
violet() and pink() now fixed.
we may have to return to noise_kasdin with a new issue - I'm not so sure about the current Noise() API...
closing this for now.
